# Generated by Django 5.2.8 on 2025-12-02 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('equipment_type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('other', 'Other')], default='barbell', max_length=20)),
                ('primary_muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body')], max_length=20)),
                ('secondary_muscle_groups', models.CharField(blank=True, help_text='Comma-separated muscle groups', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='How to perform the exercise')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
            ],
            options={
                'verbose_name': 'Global Exercise',
                'verbose_name_plural': 'Global Exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_warmup', models.BooleanField(default=False)),
                ('is_dropset', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rest_duration', models.PositiveIntegerField(blank=True, help_text='Rest time in seconds before next set', null=True)),
                ('notes', models.TextField(blank=True, help_text="E.g., 'Felt great', 'Knee pain on rep 5'")),
            ],
            options={
                'verbose_name': 'Logged Set',
                'verbose_name_plural': 'Logged Sets',
                'ordering': ['session_exercise', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('equipment_type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('other', 'Other')], default='barbell', max_length=20)),
                ('primary_muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body')], max_length=20)),
                ('secondary_muscle_groups', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Exercise',
                'verbose_name_plural': 'Custom Exercises',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LoggedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., 'Push Day A - Dec 2'", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Overall workout notes')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logged Workout',
                'verbose_name_plural': 'Logged Workouts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_type', models.CharField(choices=[('weight_at_reps', 'Best Weight at X Reps'), ('one_rep_max', 'Estimated 1RM')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveIntegerField()),
                ('estimated_1rm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.customexercise')),
                ('global_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.globalexercise')),
                ('logged_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.loggedset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text="E.g., 'Moved this later - machine was taken'")),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.customexercise')),
                ('global_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.globalexercise')),
                ('logged_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='tracker.loggedworkout')),
            ],
            options={
                'verbose_name': 'Session Exercise',
                'verbose_name_plural': 'Session Exercises',
                'ordering': ['logged_workout', 'order'],
            },
        ),
        migrations.AddField(
            model_name='loggedset',
            name='session_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='tracker.sessionexercise'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_bar_weight', models.DecimalField(decimal_places=2, default=45.0, help_text='Standard barbell weight', max_digits=5)),
                ('weight_unit', models.CharField(choices=[('lbs', 'Pounds (lbs)'), ('kg', 'Kilograms (kg)')], default='lbs', max_length=3)),
                ('default_rest_time', models.PositiveIntegerField(default=90, help_text='Default rest time in seconds')),
                ('show_plate_calculator', models.BooleanField(default=True)),
                ('show_warmup_sets', models.BooleanField(default=True, help_text='Display warmup sets in history')),
                ('rest_timer_sound', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_sets', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('target_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, help_text="E.g., 'Superset with tricep extensions'")),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.customexercise')),
                ('global_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.globalexercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_exercises', to='tracker.workoutplan')),
            ],
            options={
                'verbose_name': 'Planned Exercise',
                'verbose_name_plural': 'Planned Exercises',
                'ordering': ['workout_plan', 'order'],
            },
        ),
        migrations.AddField(
            model_name='loggedworkout',
            name='workout_plan',
            field=models.ForeignKey(blank=True, help_text='The plan this workout was based on (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.workoutplan'),
        ),
    ]
