# Generated by Django 5.2.8 on 2025-12-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='weight_increment_type',
            field=models.CharField(choices=[('plate', 'Plate Loading (2.5, 5, 10, 25, 35, 45 lbs)'), ('pin', 'Pin/Cable (1 lb increments)')], default='plate', help_text='How weight is incremented on this exercise', max_length=10),
        ),
        migrations.AddField(
            model_name='globalexercise',
            name='weight_increment_type',
            field=models.CharField(choices=[('plate', 'Plate Loading (2.5, 5, 10, 25, 35, 45 lbs)'), ('pin', 'Pin/Cable (1 lb increments)')], default='plate', help_text='How weight is incremented on this exercise', max_length=10),
        ),
    ]
