# Generated by Django 5.2.8 on 2025-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_customexercise_weight_increment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='rest_before_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Rest time in seconds before starting this exercise', null=True),
        ),
    ]
